final_project/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('',home, name='home'),
    path('airline_detail/<str:attribute>',airline_detail,name='airline_detail'),
    # path('query/<str:airline_name>',query_local,name='query'),
    path('results/',display_query_result,name='display_query_results'),




]

masih_belajar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('final_project.urls','final_project'),namespace='final_project')),
]

LAW_A1_REST/models.py
from django.db import models

# Create your models here.

LAW_A1_WEB/models.py
from django.db import models

# Create your models here.

final_project/models.py
from django.db import models

# Create your models here.

LAW_A1_REST/views.py
from django.shortcuts import render

# Create your views here.

LAW_A1_WEB/views.py
from django.shortcuts import render

# Create your views here.

final_project/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
import SPARQLWrapper
import pprint
from difflib import SequenceMatcher
from rdflib import Graph, URIRef
from rdflib.namespace import RDFS, SKOS
from .rdf_utils import dbpedia_query,query_local_gema


#tes
memoization = {}



def home(request):
    html = 'homepage.html'
    return render(request,html)

def string_is_similar(a,b):
    return SequenceMatcher(None, a, b).ratio()


def airline_detail(request,attribute):



    key = ["name", "country", "isActive", "callsign", "iata", "icao"]
    attributes = [(x.replace("%20"," ")).replace("_"," ") for x in  attribute.split('&')]

    response = dict(zip(key,attributes))
    dbpedia_query_res = dbpedia_query(response['name'])
    pp = pprint.PrettyPrinter(indent=1)
    pp.pprint(dbpedia_query_res)
    index_of_right_airline = 0
    highest_similarity_ratio = 0

    if(len(dbpedia_query_res) >0):


        for airline in dbpedia_query_res:
            current_score = string_is_similar(airline['AirlineName']['value'], response['name'])
            if ( current_score > highest_similarity_ratio):
                highest_similarity_ratio =current_score
                index_of_right_airline = dbpedia_query_res.index(airline)
        the_right_airline = dbpedia_query_res[index_of_right_airline]
        if ('abstract' in the_right_airline):

            response['abstract'] = the_right_airline['abstract']['value']
        else:
            response['abstract'] = " - "
        if ('comment' in the_right_airline):

            response['comment'] = the_right_airline['comment']['value']
        else:
            response['comment'] = " - "
        if ('FleetSize' in the_right_airline):

            response['fleet_size'] = the_right_airline['FleetSize']['value']
        else:
            response['fleet_size'] = " - "
        if ('Headquarter' in the_right_airline):

            response['headquarter_link'] = the_right_airline['Headquarter']['value']
            response['headquarter'] = response['headquarter_link'].split("/")[-1].replace('_', " ")
        else:
            response['headquarter_link'] = " - "
            response['headquarter_link'] = " - "
        if ('Slogan' in the_right_airline):

            response['slogan'] = the_right_airline['Slogan']['value']
        else:
            response['slogan'] = " - "

        if ('AirlineName' in the_right_airline):

            response['name'] = the_right_airline['AirlineName']['value'].replace('_'," ")
        if ('hubAirport' in the_right_airline):
            response['hub_airport_link'] = the_right_airline['hubAirport']['value']
            response['hub_airport'] = response['hub_airport_link'].split("/")[-1].replace('_', " ")
        else:
            response['hub_airport_link'] = " - "
            response['hub_airport'] = " - "





    print('the right airline:\n\n',the_right_airline)




    if (response['isActive'].lower() == 'yes'):
        response['status'] = 'Active'
    else:
        response['status'] = 'Deceased'
    print('attribute obtained:\n', response)
    html = 'infobox.html'
    return render(request,html,response)




def display_query_result(request):
    response = {}

    print('current method:\n',request.method)
    html = 'resultspage.html'
    if (request.method == 'POST'):
        query_results = query_local_gema(request.POST['airlineName'])
        paginator = Paginator(query_results, 7)
        memoization['paginator_object'] = paginator
        response['query_results'] =  memoization['paginator_object'].page(1)
        print('query_result:\n',response['query_results'])
        print('len query result:\n',len(response['query_results']))
    else:
        current_page = request.GET.get('page')
        print('current page:\n',current_page)
        response['query_results'] = memoization['paginator_object'].page(current_page)
    return  render(request,html,response)

templates/homepage.html
<!DOCTYPE html>
{% load static %}
{# {% load staticfiles %}#}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Masih Belajar</title>
    <script src="{% static 'js/script.js' %}"></script>
    <link href="{% static 'css/homepage.css' %}" rel="stylesheet">

</head>
<body>

<div id="sandbox">

  <div class="sideb">
    <h2 class="theme-color">Semantic Airlines</h2>
    <p class="text-large theme-color">Providing airline information just as your request!</p>
      <form action="{% url 'final_project:display_query_results' %}" method="post">

           {%  csrf_token %}

           <input class="search" placeholder="Search" id="airlineName" name="airlineName" />

        <button class="sort" data-sort="jobTitle">
            Search
            </button>

      </form>

    <div class="mobFilter"><i class="fas fa-sliders-h"></i></div>
{#    <div class="porpSection">#}
{#      <button class="xbutton">X</button>#}
{#      <div class="sortSection">#}
{#      <h3>Sort By:</h3>#}
{#      <button class="sort" data-sort="jobTitle">#}
{#    Sort by Job Title#}
{#  </button>#}
{#      <button class="sort" data-sort="datePosted">#}
{#    Sort by Date Posted#}
{#  </button>#}
{#    </div>#}
{#    <div class="filterSection">#}
{#      <div class="filter">#}
{#        <h3>Filter Opening by Location</h3>#}
{#        <select id="location-filter" class="location selectlist">#}
{#      <option selected="selected" value="">All Locations</option>#}
{#      <option value="Hyderabad">Hyderabad</option>#}
{#      <option value="Bengaluru">Bengaluru</option>#}
{#      <option value="Seattle">Seattle</option>#}
{#      <option value="Dubai">Dubai</option>#}
{#      <option value="London">London</option>#}
{#    </select>#}
{#      </div>#}
{#      <div class="filter">#}
{#        <h3>Filter Opening by Job Type</h3>#}
{#        <select id="type-filter" class="jobtypefilter selectlist">#}
{#      <option selected="selected" value="">All Job Types</option>#}
{#      <option value="Full Time">Full Time</option>#}
{#      <option value="Permanent">Permanent</option>#}
{#      <option value="Part Time">Part Time</option>#}
{#    </select>#}
{#      </div>#}
{#    </div>#}
  </div>
   </div>
  <div class="listb">
    <ul class="list" id="list">


    </ul>

  </div>
</div>

</body>
</html>

templates/infobox.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="{% static 'css/infobox.css' %}" rel="stylesheet">
     <script src="{% static 'js/script.js' %}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Red+Hat+Text:400,700&display=swap" rel="stylesheet">

    <title>Airline Detail</title>
</head>
<body>
<div class="container">
    <div class="row valign-wrapper card-area">
        <div class="col s6">
            <h2>{{ name }} </h2>

        </div>


        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title indigo-text text-darken-4">{{ title }}</span>
                </div>
                <div class="divider"></div>

                <div class="card-content">

                     <p><b>IATA : </b> {{ iata }}</p>
                    <p><b>ICAO : </b> {{ icao }}</p>
                    <p><b>Country Of Origin : </b> {{ country }}</p>
                    <p><b>Status : </b> {{ status }}</p>
                     <p><b>Callsign : </b> {{ callsign }}</p>

                     <p><b>Fleet Size : </b> {{ fleet_size }}</p>

                     <p><b>Headquarter : </b> <a href="{{ headquarter_link }}" target="_blank">{{ headquarter }}</a></p>
                    <p><b>Hub Airport : </b> <a href="{{ hub_airport_link }}" target="_blank">{{ hub_airport }}</a></p>
                    <p><b>Slogan : </b> {{ slogan }}</p>


                    <div class="section">
                        <p><b></b></p>

                        <table class="" id="billboard">
                            <thead>
                            <tr>
{#                                {% for x in byear %}#}
{##}
{#                                    <th>#}
{#                                        {{ x }}#}
{#                                    </th>#}
{##}
{#                                {% endfor %}#}
                            </tr>

                            </thead>
                            <tbody>
                            <tr>
{#                                {% for y in brank %}#}
{##}
{#                                    <td>#}
{#                                        {{ y }}#}
{#                                    </td>#}
{##}
{#                                {% endfor %}#}
                            </tr>
                            </tbody>
                        </table>
                    </div>

                </div>



                <div class="card-tabs">
                    <ul class="tabs tabs-fixed-width">
                        <li class="tab"><a class="active indigo-text text-darken-4" href="#abstract-content">ABSTRACT</a></li>
                        <li class="tab"><a class = "indigo-text text-darken-4" href="#lyrics-content">COMMENTS</a></li>

                    </ul>
                </div>




                <div class="card-content scroll-box indigo lighten-4">
                    <div id="abstract-content">{{ abstract }}</div>
                    <div id="lyrics-content">
                        <div class="lyric-section">{{ comment }}</div>
                    </div>
                </div>



            </div>

        </div>
    </div>
</div>
</div>

</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    //var instance = M.Tabs.init(el, options);

    $(document).ready(function(){
        $('.tabs').tabs();
    });
</script>
</html>

templates/resultspage.html
<!DOCTYPE html>
{% load static %}
{# {% load staticfiles %}#}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Masih Belajar</title>
    <script src="{% static 'js/script.js' %}"></script>
    <link href="{% static 'css/homepage.css' %}" rel="stylesheet">

</head>
<body>

<div id="sandbox">

  <div class="sideb">
    <h2 class="theme-color">Semantic Airlines</h2>
    <p class="text-large theme-color">Providing airline information just as your request!</p>
    <form action="{% url 'final_project:display_query_results' %}"  method="post">

           {%  csrf_token %}

           <input class="search" placeholder="Search" id="airlineName" name="airlineName" />

        <button class="sort" data-sort="jobTitle">
            Search
            </button>

      </form>
    <div class="mobFilter"><i class="fas fa-sliders-h"></i></div>
{#    <div class="porpSection">#}
{#      <button class="xbutton">X</button>#}
{#      <div class="sortSection">#}
{#      <h3>Sort By:</h3>#}
{#      <button class="sort" data-sort="jobTitle">#}
{#    Sort by Job Title#}
{#  </button>#}
{#      <button class="sort" data-sort="datePosted">#}
{#    Sort by Date Posted#}
{#  </button>#}
{#    </div>#}
{#    <div class="filterSection">#}
{#      <div class="filter">#}
{#        <h3>Filter Opening by Location</h3>#}
{#        <select id="location-filter" class="location selectlist">#}
{#      <option selected="selected" value="">All Locations</option>#}
{#      <option value="Hyderabad">Hyderabad</option>#}
{#      <option value="Bengaluru">Bengaluru</option>#}
{#      <option value="Seattle">Seattle</option>#}
{#      <option value="Dubai">Dubai</option>#}
{#      <option value="London">London</option>#}
{#    </select>#}
{#      </div>#}
{#      <div class="filter">#}
{#        <h3>Filter Opening by Job Type</h3>#}
{#        <select id="type-filter" class="jobtypefilter selectlist">#}
{#      <option selected="selected" value="">All Job Types</option>#}
{#      <option value="Full Time">Full Time</option>#}
{#      <option value="Permanent">Permanent</option>#}
{#      <option value="Part Time">Part Time</option>#}
{#    </select>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
   </div>
  <div class="listb">
    <ul class="list" id="list">
        {%  if query_results|length > 0 %}
             {% for airline in query_results %}

                  <li href="http://google.com/" target="_blank" >

                  <a class = "applyyLink" href="{% url 'final_project:airline_detail' airline.url %}" target="_blank">
               <h3 class="jobTitle">{{ airline.name }}</h3>
                </a>

                 <div class="bottomBox">
              <div class="left-part">
                    <p class="jobType">IATA: </p>
                    <p class="jobLocation">{{ airline.iata }}</p>
                    <p class="jobType">ICAO: </p>
                    <p class="jobLocation">{{ airline.icao }}</p>
                </div>
               <div class="dateBox">
                   <p class="datePosted">Active:  {{ airline.isActive}}</p>
                </div>
            </div>



                 </li>
             {% endfor %}

        {%  endif %}


    </ul>
  {% if query_results.has_other_pages %}
    <div class="lpagignate">
        <span class="jPaginateBack page-arrow"><</span>
       <ul class="pagination">
    {% if query_results.has_previous %}
      <li><a href="?page={{ query_results.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in query_results.paginator.page_range %}
      {% if query_results.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if query_results.has_next %}
      <li><a href="?page={{ query_results.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
        <span class="jPaginateNext page-arrow">></span>
    </div>
  {% endif %}
  </div>
</div>


</body>
</html>